name: Check-out job

on: workflow_dispatch

jobs:
  Check-out-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show the files
        run: ls -lrth

      - name: Show the file
        run: cat Github-Actions-practice.txt
