name: Simple Github Actions file

on: workflow_dispatch

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        run: actions/checkout@v4

      - name: Build a arifact
        run: echo "building a artifact"

      - name: Show linux commands
        run: |
          pwd
          date
          uptime
          uname
          echo "hii Im Dhage Anil Kumar" > anil.txt
          ls -lrth
          cat anil.txt
          cp anil.txt kumar.txt
          cat kumar.txt
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the artifact
        run: echo "deploying the artifact"

      - name: Done
        run: echo "artifact deployed done"
