name: Varibables, concurrency, Multi jobs

on: workflow_dispatch

concurrency:
  group: main-branch-group
  cancel-in-progress: true

env:
  BRAND: Workflow---level
  COMPANY: Amul----Branc----workflow---level

jobs:
  Simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        run: |
          touch anil.txt
          echo "Hii Im Dhage Anil Kumar and Im Learning Devops with githubactions" > anil.txt
          cat anil.txt

  Step-Level-varibables:
    runs-on: ubuntu-latest
    needs: Simple-job
    steps:
      - name: variables
        env:
          CITY: Adoni
          COUNTRY: India
        run: |
          echo "Hii my name is Dhage Anil Kumar"
          echo "And I current address is $CITY"
          echo "And Im living in $COUNTRY"

  Job-Level-Variables:
    runs-on: ubuntu-latest
    env:
      VARIABLE: DHage ANil Kumar Variables
      NAME: DHAGE ANIL KUMAR
    needs: Step-Level-varibables
    steps:
      - name: Job level Variables
        run: |
          echo "Hiii this job is $VARIABLE level"
          echo "Checking for second time $VARIABLE"
          echo "My Name is $NAME"

      - name: Second job level
        run: |
          echo "Second job level $VARIABLE"
          echo "Verifying the third time $VARIABLE"
          echo "My name is second name is $NAME"

  workflow-level-variables:
    runs-on: ubuntu-latest
    needs: Job-Level-Variables
    steps:
      - name: Workflow level
        run: |
          echo "This job is Workflow level with $BRAND"
          echo "This second job as workflow level company name is $COMPANY"

      - name: second workflow level
        run: |
          echo "Hii this is Dhage Anil Kumar and status is $BRAND"
          echo "Hii this is DHage Anil Kumar and working in company is $COMPANY"

  upload-artifact:
    runs-on: ubuntu-latest
    needs: workflow-level-variables
    steps:
      - name: Create a file
        run: echo "This is upload a artifact" > artifact.txt
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: artifact.txt

  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Show th file
        run: cat artifact.txt


  Repo-level-varibables:
    runs-on: ubuntu-latest
    needs: download-artifact
    steps:
      - name: Repo-level-Variables
        run: |
          echo "Hii This is Repo level variables ${{ vars.ANIL }}"
          echo "Hii this second steo Repo level varibables ${{ vars.KUMAR }}"

      - name: Repo-level-Secrets
        run: |
          echo "This is screts in file name is ${{ secrets.FILE }}"
          echo  "This is second file name is ${{ secrets.TEXT }}"
        
    






        
  
