name: Build, Test and Deploy pipeline code

on: workflow_dispatch

jobs:
  Build-Test-Deploy-Matrix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [11, 17]
        env: [dev, prod]

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Set-Up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Build the Artifact
        run: |
          echo "java-OS: ${{ matrix.os }}"
          echo "java-Version: ${{ matrix.node }}"
          echo "java-env: ${{ matrix.env }}"
          echo "Building the artifact is done"

      - name: Testing the Application
        run: |
          echo "testing the application..."
          echo "test is done."

      - name: Deploying the Application
        run: |
          echo "Deploying the application..."
          echo "Deployed is done"





















      
