name: Exclude Matrix

on: workflow_dispatch

jobs:
  Exclude-Matrix:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [11, 18]
        
        exclude:
          - os: windows-latest
            node: 18
    steps:
      - name: Display the OS
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "version: ${{ matrix.node }}"
