name: Exclude Matrix OS and Node

on: workflow_dispatch

jobs:
  Exclude-Matrix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [16, 18]
        exclude:
          - os: ubuntu-latest
            node: 16
            

    steps:
      - name: Matrix with exclude
        run: |
          echo "Running on: ${{ matrix.os }}"
          echo "version is: ${{ matrix.node }}"
          
