name: File Changes in GitHub

on:
  push:
    paths:
      - devops.txt

jobs:
  file-changes:
    runs-on: ubuntu-latest

    steps:
      - name: File changed
        run: echo "devops.txt changed..."
