name: Java Setup Matrix

on:
  workflow_dispatch:

jobs:
  Java-setup-Matrix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        java: [11, 12]
        env: [dev, prod]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Display Matrix
        run: |
          echo "Java Version: ${{ matrix.java }}"
          echo "Environment: ${{ matrix.env }}"
          echo "Operating System: ${{ matrix.os }}"
