name: Job Level Vars

on: workflow_dispatch

jobs:
  Job-Level-Vars:
    runs-on: ubuntu-latest
    env:
      Name: Dhage Anil Kumar
      Company: Ranstand
      Role: Auditor
      Level: Job-Level

    steps:
      - name: Display the Name
        run: |
          echo "My Name is: $Name"

      - name: Display the Company Name
        run: |
          echo "My Company Name is: $Company"

      - name: Display the Role
        run: |
          echo "My Role is: $Role"

      - name: Display the Level
        run: |
          echo "Level is: $Level"

      - name: This is the Step level vars
        env:
          Name: Kumar
          Company: Step
          Role: Stepmom

        run: echo "This is the step level vars details name is $Name, $Company, $Role"


        
