name: Job Level Time Out

on: workflow_dispatch

jobs:
  Job-Level-Timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Job level timeout-minutes
        run: |
          echo "started..."
          sleep 30
          echo "finished"
