name: Job Level Vars

on: workflow_dispatch

jobs:
  Job_level_Vars:
    runs-on: ubuntu-latest
    env:
      NAME: Dhage Anil Kumar
      COMPANY: Randstand
      Role: Auditor

    steps:
      - name: Job level vars
        run: |
          echo "My name is: $NAME"
          echo "Im working in: $COMPANY"
          echo "My role is: $ROLE"

      - name: Single line step level vars
        env:
          CITY: Adoni
          COUNTRY: India
        run: echo "Im living in $CITY, $COUNTRY and My name is $NAME."
