name: Job Level Vars

on: workflow_dispatch

jobs:
  Job-Level-Vars:
    runs-on: ubuntu-latest
    env:
      Name: Dhage Anil Kumar
      Company: Randstand
      Role: Auditor
      Country: India
      State: Andhra Pradesh

    steps:
      - name: Job Level Vars
        run: |
            echo "My Name is: $Name"
            echo "Working in: $Company"
            echo "Role is: $Role"

      - name: Details
        run: |
          echo "My country is: $Country"
          echo "My State is: $State"
