name: Matrix and Node Version with Region

on: workflow_dispatch

jobs:
  Matrix-Node-Regions:
    runs-on: ${{ matrix.region }}
    strategy:
      matrix:
        region: [us-east-1, us-west-1, ap-south-1]
        env: [dev, prod]

    steps:
      - name: AWS Regions
        run: |
          echo "AWS Regions: ${{ matrix.region }} and shows env: ${{ matrix.env }}"
          echo "Hii This is Matrix and env regions"
          echo "Hii My name is Dhage Anil Kumar"
          pwd
          time
          date
          uptime
          sleep 10s
