name: Matrix

on: workflow_dispatch

jobs:
  Matrix:
    runs-on: ${{ matrix.anil }}
    strategy:
      matrix:
        anil: [ubuntu-latest, windows-latest]
        node: [18, 16]
    steps:
      - name: Print OS
        run: echo "Running on... ${{ matrix.anil }}"
