name: Matrix and Node Version

on: workflow_dispatch

jobs:
  Matrix-Node:
    runs-on: ${{ matrix.anil }}
    strategy:
      matrix:
        anil: [ubuntu-latest, windows-latest]
        node: [16, 18]

    steps:
      - name: Print OS and version
        run: |
          echo "Running Version: ${{ matrix.node }}"
          echo "Running OS: ${{ matrix.anil }}"
