name: Matrix OS and Version

on: workflow_dispatch

jobs:
  Matrix-OS-Versions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [11, 18]

    steps:
      - name: print the OS
        run: "Running in: ${{ matrix.os }}"

      - name: Print Versions
        run: "Versions: ${{ matrix.version }}"
