name: Multiple lines job

on: workflow_dispatch

jobs:
  Multiple-Lines:
    runs-on: ubuntu-latest

    steps:
      - name: First multiple lines
        run: |
          echo "Hii ra yerri puka"

      - name: second multiple lines
        run: |
          echo "Hii ra pichi puka"
          echo "Hii ra puka"

      - name: Third multiple lines
        run: |
          echo "Edi three lines jobs"
          echo "Anduke nenu three lines code rasanu"
          echo "done ra puka"
