name: Multiple jobs

on: workflow_dispatch

jobs:
  Build-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Build job
        run: |
          echo "building the artifact..."
          echo "done"

      - name: Testing the job
        run: |
          echo "Testing the artifact..."
          echo "done"

      - name: Deploy the job
        run: |
          echo "Deploying the artifact..."
          echo "Done"
