name: Mutli line Github Actions

on: workflow_dispatch

jobs:
  Build-step:
    runs-on: ubuntu-latest
    steps:
      - name: Build the artifact
        run: echo "building the artifact..."

  Test-step:
    runs-on: ubuntu-latest
    steps:
      - name: Testing the artifact
        run: |
          echo "Hii"
          echo "Testing the artifact..."

  Deploy-step:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the artifact
        run: echo "Deploying the artifact..."
