name: Parellel fail fast fail

on: workflow_dispatch

jobs:
  Parellel-fail-Fast:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [1, 2, 3, 4, 5]

    steps:
      - name: Checking for parallel
        run: |
          echo "Java-version is: ${{ matrix.os }}"
