name: Matrix with Region

on:
  workflow_dispatch:

jobs:
  Matrix-Region:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region: [india, usa]

    steps:
      - name: Display the Region
        run: echo "Running in ${{ matrix.region }}"
