name: Matrix with region

on: workflow_dispatch

jobs:
  Matrix-Regions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region: [chrome, facebook]

    steps:
      - name: Display the regions
        run: echo "running in ${{ matrix.region }}"
