name: Repo level Github Actions

on: workflow_dispatch

jobs:
  Repo-Level-Vars:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Level vars
        run: |
          echo "NAME=${{ vars.NAME }}"
          echo "COMPANY=${{ vars.COMPANY }}"
          echo "ROLE=${{ vars.ROLE }}"

      - name: Secrets Vars
        run: |
          SAL: ${{ secrets.SAL }}
          INCREMENTAL: ${{ secrets.INCREMENTAL }}
