name: Repo level Github Actions

on: workflow_dispatch

jobs:
  Repo-Level-Vars:
    runs-on: ubuntu-latest
    steps:
      - name: Repo Level vars
        run: |
          echo "My name is: $NAME"
          echo "Im working in: $COMPANY"
          echo "My role is: $ROLE"

      - name: Secrets Vars
        run: |
          echo "My salary is: $SAL"
          echo "My incremental salary is: $INCREMENTAL"
