name: Repo level vars

on: workflow_dispatch

jobs:
  Repo-Level-Vars:
    runs-on: ubuntu-latest
    steps:
      - name: Repo level vars
        run: |
          echo "My Secret is: ${{ secrets.SEC }}"
          echo "My another Secret is: ${{ secrets.CREAT }}"

      - name: Repo level Vars Second
        run: |
          echo "My Name is: ${{ vars.NAME }}"
          echo "My ROle is: ${{ vars.VARS }}"
