name: Repo Level Secrets and Variables

on:
  workflow_dispatch:

jobs:
  Repo-Level-Vars:
    runs-on: ubuntu-latest

    steps:
      - name: Display Repository Secrets
        run: |
          echo "My Secret is: ${{ secrets.SEC }}"
          echo "My Another Secret is: ${{ secrets.CREAT }}"

      - name: Display Repository Variables
        run: |
          echo "My Name is: ${{ vars.NAME }}"
          echo "My Role is: ${{ vars.VARS }}"
