name: Repo level vars

on: workflow_dispatch

jobs:
  Repo-Level-Vars:
    runs-on: ubuntu-latest

    steps:
      - name: Repo Level Vars
        run: |
          echo "Employee Name is: ${{ secrets.NAME }}"

  Second-Repo-Level-Vars:
    runs-on: ubuntu-latest

    steps:
      - name: Second level vars in Repo
        run: |
          echo "Employee Company is: ${{ vars.COMPANY }}"
          echo "Employee Role is: ${{ vars.ROLE }}"

          
