name: Repo Level Vars

on:
  workflow_dispatch:

jobs:
  Name-Vars:
    runs-on: ubuntu-latest
    env:
      Country: India

    steps:
      - name: Name
        run: |
          echo "My Name is: ${{ secrets.NAME }}"
          echo "My Country Name is: $Country"

  Company-Vars:
    runs-on: ubuntu-latest
    needs: Name-Vars

    steps:
      - name: Company
        run: |
          echo "My Company Name is: ${{ vars.COMPANY }}"

  Role-Vars:
    runs-on: ubuntu-latest
    needs: Company-Vars

    steps:
      - name: Role
        env:
          State: Andhra Pradesh
        run: |
          echo "My Role is: ${{ vars.ROLE }}"
          echo "My State Name is: $State"
