name: Repo Level Variables

on:
  workflow_dispatch:

jobs:
  repo-level-vars:
    runs-on: ubuntu-latest

    steps:
     - name: Test Variables
       run: |
          echo "COMPANY=${{ vars.COMPANY }}"
          echo "ROLE=${{ vars.ROLE }}"
          echo "Name=${{ secrets.NAME }}"
          
