name: Simple Secrets and Variables in repo-level

on:
  workflow_dispatch:

jobs:
  sec-vars-repo-level:
    runs-on: ubuntu-latest

    steps:
      - name: Showing the Secrets
        run: |
          echo "My name is ${{ secrets.NAME }} and password is ${{ secrets.PASSWORD }}" > anil.txt
          cat anil.txt

      - name: Showing the Variables
        run: |
          echo "My name is ${{ vars.NAME }} and my role is ${{ vars.VALUES }}" > kumar.txt
          cat kumar.txt
