name: Simple Shell Script job

on: workflow_dispatch

jobs:
  Shell-Script:
    runs-on: ubuntu-latest

    steps:
      - name: First check out the shell script
        uses: actions/checkout@v4

      - name: Second display the shell script
        run: ls -lrth

      - name: Give the permission for shell script
        run: chmod u+x shellscript.sh

      - name: Excuete the shell script
        run: ./shellscript.sh
