name: Simple Github Actions Job

on: workflow_dispatch

jobs:
  Simple-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        run: touch anil.txt

      - name: Insert some data in that file
        run: echo "Hii Im Dhage Anil Kumar and Im learning Github Actions with Devops" > anil.txt

      - name: Show the file
        run: cat anil.txt

      - name: Some Linux commands
        run: sleep 10s
