name: Simple job

on: workflow_dispatch

jobs:
  Simple-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Simple job
        run: pwd

      - name: Second job
        run: echo "Dhage Anil Kumar" > anil.txt cat anil.txt
