name: Single Job Github Actions

on: workflow_dispatch

jobs:
  Single-job:
    runs-on: ubuntu-latest
    steps:
      - name: Display some linux commands
        run: |
          pwd
          touch anil.txt
          ls -lrth
          uptime
          sleep 10
