name: Three stages job

on: workflow_dispatch

jobs:
  Build-Step:
    runs-on: ubuntu-latest

    steps:
      - name: Build the application
        run: |
          echo "building the artifact..."
          echo "Done"

  Test-Step:
    runs-on: ubuntu-latest

    steps:
      - name: Testing the appllication
        run: |
          echo "Testing the application..."
          echo "done"

  Deploy-Step:
    runs-on: ubuntu-latest

    steps:
      - name: Deployed the application
        run: |
          echo "deploying the application..."
          echo "done"







          
