name: Step Level Vars

on: workflow_dispatch

jobs:
  Step-level-Vars:
    runs-on: ubuntu-latest

    steps:
      - name: Step level Vars
        env:
          Name: Dhage Anil Kumar
          Company: Ranstand
          Role: Auditor
        run: |
          echo "Employee Name is: $Name"
          echo "Employee working company name is: $Company"
          echo "Employee Role is: $Role"
