name: Step level Vars

on: workflow_dispatch

jobs:
  Step-Level-Vars:
    runs-on: ubuntu-latest

    steps:
      - name: This is the step level vars
        env:
          Name: Dhage Anil Kumar
          Company: Ranstand
          Role: Auditor

        run: |
          echo "My Name is: $Name"
          echo "My Company Name is: $Company"
          echo "My Role is: $Role"
