name: Step Level Vars

on: workflow_dispatch

jobs:
  Step-Level-Vars:
    runs-on: ubuntu-latest
    steps:
      - name: Step level vars
        env:
          NAME: Dhage Anil Kumar
          COMPANY: Ranstand
          ROLE: Auditor
        run: |
          echo "My Name is: $NAME"
          echo "Im Working in: $COMPANY"
          echo "Im supporting role is: $ROLE"

      - name: Show some linux commands
        run: sleep 30
