name: Three Stage Steps

on: workflow_dispatch

jobs:
  Build-Step:
    runs-on: ubuntu-latest

    steps:
      - name: This is Build a maven artifact
        run: |
          echo "Building the artifact..."
          echo "done"

  Test-Job:
    runs-on: ubuntu-latest
    needs: Build-Step

    steps:
      - name: This is the Test for artifact
        run: |
          echo "Testing the artifact..."
          echo "done"

  Deploy-Job:
    runs-on: ubuntu-latest
    needs: Test-Job

    steps:
      - name: This is Deploy artifact into EKS
        run: |
          echo "Deploying the artifact into EKS..."
          echo "Done"
