name: Upload and Download Artifact

on: workflow_dispatch

jobs:
  Upload-the-Artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Upload the Artifact
        uses: actions/upload-artifact@v4
        with:
          name: datafile
          path: Github-Actions-practice.txt

  Download-Artifact:
    runs-on: ubuntu-latest
    needs: Upload-the-Artifact

    steps:
      - name: Donwload the Artifact
        uses: actions/download-artifact@v4
        with:
          name: datafile

      - name: Display the Artifact
        run: cat Github-Actions-practice.txts
  
