name: Without concurrency

on: workflow_dispatch

jobs:
  simple-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Simple workflow
        run: |
          echo "Hii Im DHage Anil kumar" > anil.txt
          pwd
          ls -lrth
          time
          date
          uptime
          sleep 30s

      - name: Completed withou concurrency
        run: echo "Done"
