name: Workflow level variables

on: workflow_dispatch

jobs:
  workflow-level-var:
    runs-on: ubuntu-latest

    env:
      CITY: Adoni
      COUNTRY: India

    steps:
      - name: Workflow level vars
        run: echo "Hi Im Dhage Anil Kumar and Im from $CITY and I lives in $COUNTRY" > anil.txt

      - name: Show the file
        run: |
          pwd
          ls -lrth
          time
          cat anil.txt
          uptime
          sleep 5s
