name: Workflow level Vars

on: workflow_dispatch

env:
  NAME: Dhage Anil Kumar
  COMPANY: Ranstand
  ROLE: Auditor and QA
  PROJECT: Github Actions
  ENV: Prod

jobs:
  Workflow-level-Vars:
    runs-on: ubuntu-latest
    env:
      CITY: Adoni
      COUNTRY: India
    steps:
      - name: Workflow level vars
        run: |
          echo "My Name is: $NAME"
          echo "My company name is: $COMPANY"
          echo " My role is: $ROLE"

      - name: Workflow second level vars
        run: |
          echo "My Project name is: $PROJECT"
          echo "My supporting role is: $ENV"

      - name: Step level vars
        env:
          BRAND: Slik
          COM: ITC
        run: |
          echo "Im smoking brand name is: $BRAND"
          echo "The company is: $COM"

      - name: Job level Vars
        run: |
          echo "Job level Anil kumar is living in $CITY and working in $COUNTRY"
          echo "$CITY and $COUNTRY"
